"""
Django settings for arcx_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# 1. Define the BASE_DIR (which points to the folder containing manage.py)
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Force load_dotenv to look specifically inside BASE_DIR for your .env file
load_dotenv(BASE_DIR / '.env')

# ... the rest of your settings.py stays the same ...
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-lr&(eza=fwaz=szk_$@5ei944vbzcz3s@%8a!65$d80$458$=+")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG      = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Add your nested app here
    #phase 3 dependencies

    "rest_framework",
    "rest_framework_simplejwt",
    "arcx_core",
]

MIDDLEWARE = [
    "arcx_core.middleware.RequestLoggingMiddleware", # <-- ADD THIS FIRST
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "arcx_core.middleware.IdempotencyMiddleware",   # Phase 3 custom
]

ROOT_URLCONF = 'arcx_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'arcx_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE":   "django.db.backends.postgresql",
        "NAME":     os.getenv("DB_NAME",     "arcx_db"),
        "USER":     os.getenv("DB_USER",     "arcx_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST":     os.getenv("DB_HOST",     "localhost"),
        "PORT":     os.getenv("DB_PORT",     "5432"),
        "OPTIONS": {
            # Enforce UTC everywhere. Financial timestamps must be unambiguous.
            "options": "-c timezone=UTC",
        },
        "CONN_MAX_AGE": 60,  # Keep connections alive for 60s (connection pooling lite)
    }
}


# ── Django REST Framework ─────────────────────────────────────────────────────
REST_FRAMEWORK = {
    # Every endpoint requires a valid JWT unless explicitly marked public
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Consistent error shape everywhere: {"error": "...", "code": "..."}
    "EXCEPTION_HANDLER": "arcx_core.exceptions.arcx_exception_handler",
    # Decimal values must stay as strings in JSON — never floats
    "COERCE_DECIMAL_TO_STRING": True,
}
 
# ── JWT Config ────────────────────────────────────────────────────────────────
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME":  timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS":  True,     # New refresh token on every use
    "BLACKLIST_AFTER_ROTATION": False,  # Keep simple for Phase 3
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
}
 
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
USE_TZ = True
TIME_ZONE = "UTC"
 

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



"""
ARCX Logging Configuration — Phase 4
----------------------------------------

HOW DJANGO LOGGING WORKS (in 3 lines):
  Logger   → "arcx" logger emits a message
  Handler  → decides WHERE it goes (console? file? both?)
  Filter   → decides WHICH messages get through (DEBUG? INFO? ERROR only?)

ARCX uses two handlers in parallel:
  1. console  → human-readable during development (python manage.py runserver)
  2. file     → structured JSON in logs/arcx.log (permanent audit trail)

In production, you'd ADD a third handler shipping to Datadog / Loki / CloudWatch.
The logger code doesn't change — only the handlers in settings.py.
That's the power of the logging abstraction.

FILE ROTATION:
  RotatingFileHandler prevents log files from growing forever.
  maxBytes=10MB, backupCount=5 means:
    arcx.log       ← current (max 10MB)
    arcx.log.1     ← previous
    arcx.log.2     ← before that
    ...
    arcx.log.5     ← oldest kept
  Total max disk: 60MB. After that, oldest files are deleted automatically.
"""

import os

# Create the logs directory if it doesn't exist
# (logs/ should be in .gitignore — never commit log files)
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,   # Keep Django's own loggers working

    # ── Formatters ────────────────────────────────────────────────────────
    "formatters": {
        # For the console: readable prefix + the JSON payload
        "console_fmt": {
            "format": "%(asctime)s [%(levelname)s] %(message)s",
            "datefmt": "%H:%M:%S",
        },
        # For the file: raw JSON only (no extra prefix — the JSON has ts already)
        "json_fmt": {
            "format": "%(message)s",
        },
    },

    # ── Handlers ──────────────────────────────────────────────────────────
    "handlers": {
        # Handler 1: Coloured console output for development
        "console": {
            "class":     "logging.StreamHandler",
            "formatter": "console_fmt",
            "level":     "DEBUG",
        },

        # Handler 2: Rotating JSON file — the permanent audit trail
        "arcx_file": {
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    os.path.join(LOG_DIR, "arcx.log"),
            "maxBytes":    10 * 1024 * 1024,   # 10 MB per file
            "backupCount": 5,                   # Keep last 5 files
            "formatter":   "json_fmt",
            "level":       "INFO",
            "encoding":    "utf-8",
        },

        # Handler 3: Errors-only file — quick triage without reading all logs
        "error_file": {
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    os.path.join(LOG_DIR, "arcx_errors.log"),
            "maxBytes":    5 * 1024 * 1024,    # 5 MB per file
            "backupCount": 3,
            "formatter":   "json_fmt",
            "level":       "ERROR",
            "encoding":    "utf-8",
        },
    },

    # ── Loggers ───────────────────────────────────────────────────────────
    "loggers": {
        # The ARCX application logger — used by arcx_core/logger.py
        "arcx": {
            "handlers":  ["console", "arcx_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,   # Don't bubble up to Django's root logger
        },

        # Django's own request logger — useful in development
        "django.request": {
            "handlers":  ["console", "error_file"],
            "level":     "WARNING",   # Only log 4xx/5xx, not every 200
            "propagate": False,
        },

        # Silence noisy libraries
        "urllib3":    {"level": "WARNING"},
        "yfinance":   {"level": "WARNING"},
        "requests":   {"level": "WARNING"},
    },
}