# Generated by Django 5.2.6 on 2026-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcx_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_inr',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Instant liquidity fee charged on Route A withdrawals (0.1%, max $100 equivalent)', max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='settlement_date',
            field=models.DateTimeField(blank=True, help_text='For Route B (T+2 standard) withdrawals: when INR settles to bank', null=True),
        ),
    ]
