# Generated by Django 6.0.5 on 2026-05-27 06:57

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcx_core', '0002_add_fee_inr_settlement_date_to_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultAssetHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('asset_ticker', models.CharField(choices=[('SPY', 'S&P 500 ETF (Stocks)'), ('TLT', '20+ Year Treasury ETF (Bonds)'), ('GLD', 'Gold ETF')], db_index=True, max_length=10, unique=True)),
                ('total_quantity', models.DecimalField(decimal_places=18, default=Decimal('0'), help_text='Total fractional shares held. e.g. 14.502394850000000000', max_digits=28)),
                ('average_buy_price', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Weighted average purchase price in USD. Used for cost-basis analytics, NOT for NAV.', max_digits=20)),
            ],
            options={
                'verbose_name': 'Vault Asset Holding',
                'verbose_name_plural': 'Vault Asset Holdings',
                'db_table': 'vault_asset_holdings',
            },
        ),
    ]
