# Generated by Django 6.0.5 on 2026-05-27 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcx_core', '0003_add_vault_asset_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='Hashed UPI-style PIN for authorizing B2B transfers.', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='BusinessAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('alias', models.CharField(db_index=True, help_text='e.g. supplier@arcx', max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='arcx_core.user')),
            ],
            options={
                'db_table': 'business_aliases',
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('secret_key', models.CharField(help_text='Used to sign webhook payloads for security.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_config', to='arcx_core.user')),
            ],
            options={
                'db_table': 'webhook_endpoints',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transaction_id', models.UUIDField(db_index=True, help_text='ID of the related ARCX Transaction')),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='arcx_core.webhookendpoint')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
