# Generated by Django 6.0.5 on 2026-05-27 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcx_core', '0004_wallet_transaction_pin_businessalias_webhookendpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(default='PIN_RESET', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'otp_verifications',
            },
        ),
        migrations.RemoveIndex(
            model_name='kycrecord',
            name='kyc_records_user_id_88b5c0_idx',
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='pan_number',
            field=models.CharField(default='DEFAULT_PA', help_text='10-character alphanumeric PAN', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='kycrecord',
            index=models.Index(fields=['user', 'status'], name='kyc_records_user_id_a600f7_idx'),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='arcx_core.user'),
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='document_ref',
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='tier',
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='otp_verific_user_id_c740ad_idx'),
        ),
    ]
