"""
ARCX Database Models — Phase 2
--------------------------------
All tables follow the MNC-grade non-negotiables:
 
  ✓ UUIDs as primary keys (no auto-increment)
  ✓ created_at / updated_at on every table (auto-managed)
  ✓ Soft deletes via deleted_at (hard DELETE is banned in production)
  ✓ select_for_update() on every wallet write (prevents race conditions)
  ✓ Decimal fields — never Float for money (Float loses precision at ~1e15)
  ✓ Idempotency key on Transactions (safe to retry without double-charge)
 
Why UUID over Auto-Increment?
  Auto-increment exposes business intelligence:
    GET /api/v1/users/1042  → you now know they have ~1041 other users.
  UUID reveals nothing. Standard in every fintech API.
 
Why Soft Deletes?
  Hard DELETE is irreversible. In fintech, you must be able to answer:
    "Show me the full state of this account on the day of audit."
  deleted_at preserves the record. Queries filter WHERE deleted_at IS NULL.
 
Why Decimal, Not Float?
  float(0.1) + float(0.2) == 0.30000000000000004  ← actual Python output.
  Django's DecimalField maps to PostgreSQL NUMERIC(precision, scale).
  NUMERIC is exact. No rounding surprises on ₹10,00,000 transactions.
"""
 
import uuid
from django.db import models
 
 
# ─────────────────────────────────────────────────────────────────────────────
# Base Model — inherited by every table in ARCX
# ─────────────────────────────────────────────────────────────────────────────
 
class ArcxBaseModel(models.Model):
    """
    Every ARCX table gets:
      id          → UUID primary key, generated by Python (not DB sequence)
      created_at  → Set once on INSERT, never updated
      updated_at  → Updated on every SAVE automatically
      deleted_at  → NULL = active | timestamp = soft-deleted
 
    USAGE:
      # Fetch only active records (always do this)
      User.objects.filter(deleted_at__isnull=True)
 
      # Soft-delete a record (never use .delete())
      user.deleted_at = timezone.now()
      user.save(update_fields=['deleted_at', 'updated_at'])
    """
    id         = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True, db_index=True)
 
    class Meta:
        abstract = True
 
 
# ─────────────────────────────────────────────────────────────────────────────
# Users
# ─────────────────────────────────────────────────────────────────────────────
 
class User(ArcxBaseModel):
    """
    The ARCX user account.
    Note: We do NOT store passwords here. Django's auth system handles that
    separately. This table stores ARCX-specific user data.
 
    KYC Status drives what a user can do:
      pending   → can browse, cannot transact
      approved  → full access
      rejected  → read-only, cannot deposit
      suspended → frozen by compliance
    """
 
    class KycStatus(models.TextChoices):
        PENDING   = "pending",   "Pending"
        APPROVED  = "approved",  "Approved"
        REJECTED  = "rejected",  "Rejected"
        SUSPENDED = "suspended", "Suspended"
 
    email      = models.EmailField(unique=True, db_index=True)
    full_name  = models.CharField(max_length=255)
    phone      = models.CharField(max_length=20, unique=True, null=True, blank=True)
    kyc_status = models.CharField(
        max_length=20,
        choices=KycStatus.choices,
        default=KycStatus.PENDING,
        db_index=True,
    )
    is_active  = models.BooleanField(default=True, db_index=True)
 
    class Meta:
        db_table = "users"
        indexes  = [
            models.Index(fields=["email", "deleted_at"]),
            models.Index(fields=["kyc_status", "is_active"]),
        ]
 
    def __str__(self):
        return f"User({self.email}, kyc={self.kyc_status})"
 
 
# ─────────────────────────────────────────────────────────────────────────────
# Wallets
# ─────────────────────────────────────────────────────────────────────────────
 
class WalletManager(models.Manager):
    """
    Custom manager that enforces select_for_update on all write operations.
 
    CRITICAL: Never fetch a wallet for balance modification without this.
    Without select_for_update, two concurrent deposits can both read balance=100,
    both add 50, and both write 150. Correct answer is 200. This is a race condition.
 
    PostgreSQL's SELECT FOR UPDATE places a row-level lock.
    The second transaction waits until the first commits or rolls back.
 
    USAGE (always inside transaction.atomic()):
      from django.db import transaction
 
      with transaction.atomic():
          wallet = Wallet.objects.select_for_update().get(user_id=user_id)
          wallet.arcx_balance += Decimal("10.00")
          wallet.save(update_fields=["arcx_balance", "updated_at"])
    """
    def get_for_update(self, **kwargs):
        """Fetch a wallet with a row lock. Must be inside atomic()."""
        return self.select_for_update().get(**kwargs)
 
    def get_active(self, **kwargs):
        """Fetch active (non-deleted, non-frozen) wallet."""
        return self.filter(deleted_at__isnull=True, is_frozen=False).get(**kwargs)
 
 
class Wallet(ArcxBaseModel):
    """
    One wallet per user.
    Stores ARCX token balance and cost basis for P&L calculations.
 
    arcx_balance:   How many ARCX tokens the user holds.
    cost_basis_inr: Total INR the user spent to buy their current holdings.
                    Used to calculate unrealized P&L on the frontend.
    is_frozen:      True when compliance freezes an account.
                    Frozen wallets can VIEW but not transact.
 
    Precision:
      arcx_balance   → 18 decimal places (matches standard token precision)
      cost_basis_inr → 4 decimal places (sufficient for INR)
    """
    user           = models.OneToOneField(
        User, on_delete=models.PROTECT, related_name="wallet"
    )
    arcx_balance   = models.DecimalField(max_digits=28, decimal_places=18, default=0)
    cost_basis_inr = models.DecimalField(max_digits=20, decimal_places=4, default=0)
    is_frozen      = models.BooleanField(default=False, db_index=True)
 
    objects = WalletManager()
 
    class Meta:
        db_table = "wallets"
        indexes  = [
            models.Index(fields=["user", "is_frozen", "deleted_at"]),
        ]
 
    def __str__(self):
        return f"Wallet(user={self.user_id}, balance={self.arcx_balance})"
 
 
# ─────────────────────────────────────────────────────────────────────────────
# Transactions
# ─────────────────────────────────────────────────────────────────────────────
 
class Transaction(ArcxBaseModel):
    """
    Immutable ledger of every ARCX movement.
 
    Design Decisions:
      1. Immutable: Transactions are NEVER updated after creation.
         If a transaction fails, create a new REVERSAL transaction.
         The audit log must be append-only.
 
      2. Idempotency Key: Before creating a transaction, check if this key
         already exists. If yes → return the existing transaction.
         This makes the API safe to retry (network timeouts, client retries).
 
      3. nav_at_tx: Snapshot of 1 ARCX price at the exact moment of transaction.
         Critical for tax calculations. Price changes; this record doesn't.
 
      4. counterparty_wallet: For TRANSFER type transactions, points to the
         receiving wallet. NULL for DEPOSIT and WITHDRAW.
 
    Transaction Types:
      DEPOSIT   → User bought ARCX (INR → ARCX)
      WITHDRAW  → User sold ARCX  (ARCX → INR)
      TRANSFER  → User sent ARCX to another ARCX user (free, instant)
      DIVIDEND  → Overnight yield accrual (system-generated, no INR movement)
    """
 
    class TxType(models.TextChoices):
        DEPOSIT  = "deposit",  "Deposit"
        WITHDRAW = "withdraw", "Withdraw"
        TRANSFER = "transfer", "Transfer"
        DIVIDEND = "dividend", "Dividend"
 
    class Status(models.TextChoices):
        PENDING   = "pending",   "Pending"
        COMPLETED = "completed", "Completed"
        FAILED    = "failed",    "Failed"
        REVERSED  = "reversed",  "Reversed"
 
    wallet              = models.ForeignKey(
        Wallet, on_delete=models.PROTECT, related_name="transactions", db_index=True
    )
    idempotency_key     = models.UUIDField(unique=True, default=uuid.uuid4, db_index=True)
    tx_type             = models.CharField(max_length=20, choices=TxType.choices, db_index=True)
    amount_arcx         = models.DecimalField(max_digits=28, decimal_places=18)
    amount_inr          = models.DecimalField(max_digits=20, decimal_places=4)
    nav_at_tx           = models.DecimalField(max_digits=20, decimal_places=4)
    status              = models.CharField(
        max_length=20, choices=Status.choices, default=Status.PENDING, db_index=True
    )
    counterparty_wallet = models.ForeignKey(
        Wallet,
        on_delete=models.PROTECT,
        related_name="incoming_transfers",
        null=True,
        blank=True,
    )
 
    class Meta:
        db_table = "transactions"
        indexes  = [
            models.Index(fields=["wallet", "status", "created_at"]),
            models.Index(fields=["tx_type", "created_at"]),
            models.Index(fields=["idempotency_key"]),
        ]
        # Immutability guard: app-level, not DB-level, but documents intent
        ordering = ["-created_at"]
 
    def __str__(self):
        return f"Tx({self.tx_type}, {self.amount_arcx} ARCX, {self.status})"
 
 
# ─────────────────────────────────────────────────────────────────────────────
# Vault Snapshots
# ─────────────────────────────────────────────────────────────────────────────
 
class VaultSnapshot(ArcxBaseModel):
    """
    Daily photograph of the vault state.
    Written once per day by the Celery EOD task. Never updated.
 
    This is the raw data. NAVHistory derives the published NAV from it.
 
    Why store both?
      VaultSnapshot = raw source data (asset prices, allocations)
      NAVHistory    = derived output (NAV per token, published to users)
      If the NAV formula changes, you can recalculate NAVHistory
      from the original VaultSnapshot without re-fetching market data.
    """
    snapshot_date   = models.DateField(unique=True, db_index=True)
    total_value_usd = models.DecimalField(max_digits=20, decimal_places=4)
    stock_value_usd = models.DecimalField(max_digits=20, decimal_places=4)
    bond_value_usd  = models.DecimalField(max_digits=20, decimal_places=4)
    gold_value_usd  = models.DecimalField(max_digits=20, decimal_places=4)
    cash_value_usd  = models.DecimalField(max_digits=20, decimal_places=4)
    arcx_supply     = models.DecimalField(max_digits=28, decimal_places=18)
    spy_twap        = models.DecimalField(max_digits=12, decimal_places=4)
    tlt_twap        = models.DecimalField(max_digits=12, decimal_places=4)
    gld_twap        = models.DecimalField(max_digits=12, decimal_places=4)
    usd_inr_rate    = models.DecimalField(max_digits=10, decimal_places=4)
 
    class Meta:
        db_table = "vault_snapshots"
        ordering = ["-snapshot_date"]
 
    def __str__(self):
        return f"VaultSnapshot({self.snapshot_date}, total=${self.total_value_usd})"
 
 
# ─────────────────────────────────────────────────────────────────────────────
# NAV History
# ─────────────────────────────────────────────────────────────────────────────
 
class NAVHistory(ArcxBaseModel):
    """
    The official daily published NAV.
    This is what users see in their "price history" chart.
 
    report_hash: SHA256 of the full NAV report JSON (from nav_report.py).
    Stored here so any row in this table can be independently verified
    against the JSON file. Tamper-proof audit trail.
    """
    snapshot           = models.ForeignKey(
        VaultSnapshot, on_delete=models.PROTECT, related_name="nav_records"
    )
    nav_date           = models.DateField(unique=True, db_index=True)
    nav_usd            = models.DecimalField(max_digits=20, decimal_places=8)
    nav_inr            = models.DecimalField(max_digits=20, decimal_places=4)
    dividend_accrued_inr = models.DecimalField(max_digits=20, decimal_places=8, default=0)
    report_hash        = models.CharField(max_length=64, db_index=True)  # SHA256 = 64 hex chars
 
    class Meta:
        db_table = "nav_history"
        ordering = ["-nav_date"]
        verbose_name        = "NAV History Record"
        verbose_name_plural = "NAV History Records"
 
    def __str__(self):
        return f"NAV({self.nav_date}, ₹{self.nav_inr})"
 
 
# ─────────────────────────────────────────────────────────────────────────────
# KYC Records
# ─────────────────────────────────────────────────────────────────────────────
 
class KYCRecord(ArcxBaseModel):
    """
    KYC verification history for a user.
    Multiple records per user = KYC upgrade trail (Basic → Full → Accredited).
 
    KYC Tiers:
      tier_1 → Phone + Aadhaar OTP. Limit: ₹10,000/day
      tier_2 → PAN + Selfie. Limit: ₹1,00,000/day
      tier_3 → Full address proof. Limit: Unlimited
 
    document_ref: External ID from your KYC provider (e.g., DigiLocker, Onfido).
    Do NOT store the actual document. Store only the reference.
    Actual documents live in encrypted object storage (S3/GCS), never in PG.
    """
 
    class Tier(models.TextChoices):
        TIER_1 = "tier_1", "Tier 1 — Basic"
        TIER_2 = "tier_2", "Tier 2 — Standard"
        TIER_3 = "tier_3", "Tier 3 — Full"
 
    class Status(models.TextChoices):
        PENDING  = "pending",  "Pending Review"
        APPROVED = "approved", "Approved"
        REJECTED = "rejected", "Rejected"
 
    class DocumentType(models.TextChoices):
        AADHAAR  = "aadhaar",  "Aadhaar Card"
        PAN      = "pan",      "PAN Card"
        PASSPORT = "passport", "Passport"
        DL       = "dl",       "Driving License"
 
    user          = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="kyc_records"
    )
    tier          = models.CharField(max_length=10, choices=Tier.choices, db_index=True)
    status        = models.CharField(max_length=10, choices=Status.choices, db_index=True)
    document_type = models.CharField(max_length=20, choices=DocumentType.choices)
    document_ref  = models.CharField(max_length=255)   # External reference only
    verified_at   = models.DateTimeField(null=True, blank=True)
 
    class Meta:
        db_table = "kyc_records"
        indexes  = [
            models.Index(fields=["user", "tier", "status"]),
        ]
 
    def __str__(self):
        return f"KYC(user={self.user_id}, tier={self.tier}, status={self.status})"
 
 
# ─────────────────────────────────────────────────────────────────────────────
# Circuit Breaker Log
# ─────────────────────────────────────────────────────────────────────────────
 
class CircuitBreakerLog(ArcxBaseModel):
    """
    Audit log for every circuit breaker event.
    A circuit breaker is a safety halt — like a stock exchange halting trading
    when prices move too fast.
 
    ARCX has 3 tiers (from circuit_breaker.py):
      Tier 1 (Caution):    Market drop > 5%   → Slow down withdrawals
      Tier 2 (Warning):    Market drop > 10%  → Suspend new deposits
      Tier 3 (Emergency):  Market drop > 20%  → Full halt, read-only mode
 
    event_type tells you what action was taken:
      TRIGGERED  → Circuit breaker activated
      RESOLVED   → Market recovered, normal operations resumed
      OVERRIDDEN → Admin manually overrode the breaker (requires 2FA + reason)
 
    resolved_at: NULL = still active | timestamp = when normal ops resumed.
    Knowing when a breaker was ACTIVE helps answer user disputes:
      "Why couldn't I withdraw on 10th May?" → "Circuit Tier 2 was active."
    """
 
    class Tier(models.TextChoices):
        TIER_1 = "tier_1", "Tier 1 — Caution"
        TIER_2 = "tier_2", "Tier 2 — Warning"
        TIER_3 = "tier_3", "Tier 3 — Emergency"
 
    class EventType(models.TextChoices):
        TRIGGERED  = "triggered",  "Triggered"
        RESOLVED   = "resolved",   "Resolved"
        OVERRIDDEN = "overridden", "Admin Override"
 
    tier                  = models.CharField(max_length=10, choices=Tier.choices, db_index=True)
    event_type            = models.CharField(max_length=20, choices=EventType.choices)
    reason                = models.TextField()
    market_drop_pct       = models.DecimalField(max_digits=6, decimal_places=2)
    tvl_withdrawal_pct    = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True,
        help_text="% of TVL requested for withdrawal in the trigger window"
    )
    resolved_at           = models.DateTimeField(null=True, blank=True, db_index=True)
 
    class Meta:
        db_table = "circuit_breaker_log"
        ordering = ["-created_at"]
        indexes  = [
            models.Index(fields=["tier", "event_type", "created_at"]),
            models.Index(fields=["resolved_at"]),
        ]
 
    def __str__(self):
        status = "ACTIVE" if self.resolved_at is None else "RESOLVED"
        return f"CircuitBreaker({self.tier}, {self.event_type}, {status})"
 