# Generated by Django 6.0.5 on 2026-05-23 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('total_value_usd', models.DecimalField(decimal_places=4, max_digits=20)),
                ('stock_value_usd', models.DecimalField(decimal_places=4, max_digits=20)),
                ('bond_value_usd', models.DecimalField(decimal_places=4, max_digits=20)),
                ('gold_value_usd', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cash_value_usd', models.DecimalField(decimal_places=4, max_digits=20)),
                ('arcx_supply', models.DecimalField(decimal_places=18, max_digits=28)),
                ('spy_twap', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tlt_twap', models.DecimalField(decimal_places=4, max_digits=12)),
                ('gld_twap', models.DecimalField(decimal_places=4, max_digits=12)),
                ('usd_inr_rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'vault_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='CircuitBreakerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1 — Caution'), ('tier_2', 'Tier 2 — Warning'), ('tier_3', 'Tier 3 — Emergency')], db_index=True, max_length=10)),
                ('event_type', models.CharField(choices=[('triggered', 'Triggered'), ('resolved', 'Resolved'), ('overridden', 'Admin Override')], max_length=20)),
                ('reason', models.TextField()),
                ('market_drop_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tvl_withdrawal_pct', models.DecimalField(blank=True, decimal_places=2, help_text='% of TVL requested for withdrawal in the trigger window', max_digits=6, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'circuit_breaker_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tier', 'event_type', 'created_at'], name='circuit_bre_tier_40f967_idx'), models.Index(fields=['resolved_at'], name='circuit_bre_resolve_efb996_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['email', 'deleted_at'], name='users_email_5a4d2b_idx'), models.Index(fields=['kyc_status', 'is_active'], name='users_kyc_sta_8c7952_idx')],
            },
        ),
        migrations.CreateModel(
            name='NAVHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nav_date', models.DateField(db_index=True, unique=True)),
                ('nav_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('nav_inr', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dividend_accrued_inr', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('report_hash', models.CharField(db_index=True, max_length=64)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nav_records', to='core.vaultsnapshot')),
            ],
            options={
                'verbose_name': 'NAV History Record',
                'verbose_name_plural': 'NAV History Records',
                'db_table': 'nav_history',
                'ordering': ['-nav_date'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('arcx_balance', models.DecimalField(decimal_places=18, default=0, max_digits=28)),
                ('cost_basis_inr', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('is_frozen', models.BooleanField(db_index=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='core.user')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer'), ('dividend', 'Dividend')], db_index=True, max_length=20)),
                ('amount_arcx', models.DecimalField(decimal_places=18, max_digits=28)),
                ('amount_inr', models.DecimalField(decimal_places=4, max_digits=20)),
                ('nav_at_tx', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('counterparty_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='core.wallet')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.wallet')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1 — Basic'), ('tier_2', 'Tier 2 — Standard'), ('tier_3', 'Tier 3 — Full')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, max_length=10)),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('dl', 'Driving License')], max_length=20)),
                ('document_ref', models.CharField(max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_records', to='core.user')),
            ],
            options={
                'db_table': 'kyc_records',
                'indexes': [models.Index(fields=['user', 'tier', 'status'], name='kyc_records_user_id_88b5c0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'is_frozen', 'deleted_at'], name='wallets_user_id_fb696d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'status', 'created_at'], name='transaction_wallet__29f5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tx_type', 'created_at'], name='transaction_tx_type_963c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['idempotency_key'], name='transaction_idempot_d892f2_idx'),
        ),
    ]
